### ISSUE TITLE
TTH / leaf database?

### ISSUE THREAD

**Issue by btxgit** [aler9/dctoolkit#6]
Hi,   I love these libraries!  Thank you so much for releasing them - I truly appreciate it!

I'm relatively new to Go, so I think I'm struggling in a place that a more experienced coder would be done in 5 seconds... specifically, I've been trying to implement TTH root + leaf caching.  I certainly understand why you wouldn't want too much of this code in your library, but the part I'm having trouble with is the de-serialization of []byte -> TigerLeaves, which seems like it'd be a reasonable thing to add to your library... I can't seem to get Hash to append to the TigerLeaves. 
 Is this something you would add to your library at some point?  It seems like something the library will want to implement anyway...

I noticed that - so far at least - the leaves are only used for replying to "tthl" get requests.  So I could just cache the raw leaf values in a big buffer, but I wanted to check to see if you were planning to add merkel tree functions that would benefit from keeping the tthl in a tree, such as  part verification.  If not, the keeping the raw tthl buffer around would simplify things.

In any event, thank you so much for releasing such great software!  I'd been looking for a library that supports both nmdc and adc, but I didn't think I'd find anything that was as complete as yours, that was still being worked on!  Thanks you!

**Comment by aler9** [comment]
Hi, thanks for the support, i don't know if i understood correctly your question, so i'll sum up the role of TTH leaves in DC and what's the status of each related feature in this library.

TTH leaves are the Tiger hashes of each 1024 bytes of a certain file, each prefixed by 0x00.
So, if we have a 3000-bytes file, its TTH leaves are (in pseudocode):
```
{ TigerHash(0x00, file[0:1024]), TigerHash(0x00, file[1025:2048]), TigerHash(0x00, file[2049:3000]) }
```
In this library, this is performed by this function
https://godoc.org/github.com/aler9/go-dc/tiger#TreeLeaves

The TTH is the unique identifier of a certain file, and is computed with the Merkle Tree Algorithm, which uses each leave to compute a overall Tiger Hash, which is normally called TTH.
In this library, this is performed by this function
https://godoc.org/github.com/aler9/go-dc/tiger#Leaves.TreeHash

TTH leaves are useful in two situations:
* when uploading, since the downloader will usually want to know ALL the TTH leaves of the file before starting the download. In this case, we must have a big buffer of all the TTH leaves of every file, since we have to serve them when they are requested.

* when downloading, to verify each part. This library only allows a overall validation of a certain file, and at the moment doesn't support the validation of each single part. This means that if a file fails the validation, you have to download it again.

So: a raw buffer with all the TTH leaves in it is (unfortunately) always necessary, since DC is a p2p protocol and we are always both uploaders and downloaders. Regarding the missing feature, you can implement it manually by saving the boolean state of each element of each level of the Merkle Tree (validated / not validated), and re-download a certain part when it fails the test.

**Comment by btxgit** [comment]
Hi, sorry I wasn't clear in my question - I understand Merkle trees and the NMDC and ADC protocols fairly well - I was just looking for a way to support serializing the leaves + the root TTH to disk, like in DC++-based clients (hashdata.dat / hashinfo.xml).  I'm still relatively new to Go, so although I had no problem serializing the leaves to disk, I had trouble coming up with a way to go from []byte (from a disk read) to the TigerLeaves type.  It seems like without that, it would need to hash every file in your share every time (or did I miss something?)

**Comment by aler9** [comment]
Hi, sorry for the delay, i've implemented the feature you were looking for, ie the encoding/decoding of TTH leaves from/to []byte.

It's quite simple to implement it from scratch if you're familiar with Go, but since it's a very useful feature, i've integrated it into the library.

Decoding:
```
package main

import (
    dctk "github.com/aler9/dctoolkit"
)

func main() {
    byts := []byte{ ... }
    l, err := dctk.TTHLeavesLoadFromBytes(byts)
    if err != nil {
        panic(err)
    }

    fmt.Println(l)
}
```

Encoding:
```
package main

import (
    dctk "github.com/aler9/dctoolkit"
)

func main() {
    l := dctk.TigerLeaves{ ... }
    byts, err := l.SaveToBytes()
    if err != nil {
        panic(err)
    }

    fmt.Println(byts)
}
```

Hope this solves your problem, bye

**Comment by aler9** [comment]
I've also added a bunch of functions to load and save leaves from/to bytes, readers, files, you can find them in the documentation:

https://godoc.org/github.com/aler9/dctoolkit#TigerLeaves
